name: Bangla-LLM

services:
  Bangla-LLM:
    image: bangla-llm:latest
    build:
      context: ..
      dockerfile: Deployments/Dockerfile
    container_name: Bangla-LLM
    ports:
      - "9000:9000"
    env_file:
      - ../.env
    restart: unless-stopped
