services:
  bangla-llm:
    build:
      context: ..
      dockerfile: Deployments/Dockerfile
    container_name: bangla-llm
    ports:
      - "8000:8000"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    env_file:
      - ../.env
    restart: unless-stopped
